apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooms
spec:
  selector:
    matchLabels:
      app: rooms
  replicas: 2
  template:
    metadata:
      labels:
        app: rooms
    spec:
      containers:
        - name: rooms
          image: mguay/rooms
          ports:
            - containerPort: 3000